/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package banking_system;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Our
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        edtDeposit = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAreaTransactions = new javax.swing.JTextArea();
        edtBalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmHome"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 37, -1, -1));

        btnCalculate.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnCalculate.setText(" Calculate");
        btnCalculate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 183, 44));

        btnWithdraw.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnWithdraw.setText(" Withdraw");
        btnWithdraw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnWithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(btnWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 183, 44));

        edtDeposit.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        edtDeposit.setText(" Deposit");
        edtDeposit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edtDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edtDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDepositActionPerformed(evt);
            }
        });
        getContentPane().add(edtDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 183, 44));

        btnLogOut.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnLogOut.setText("Log out");
        btnLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 183, 44));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("To Our Banking System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 89, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/again.PNG")));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 157, 40, 45));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/again.PNG")));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 220, 40, 44));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/again.PNG")));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 40, 44));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/again.PNG")));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 337, 40, 44));

        tAreaTransactions.setEditable(false);
        tAreaTransactions.setColumns(20);
        tAreaTransactions.setRows(5);
        jScrollPane1.setViewportView(tAreaTransactions);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 228, 333, 161));

        edtBalance.setEditable(false);
        getContentPane().add(edtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 320, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock graphs.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        new Sign_In().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        Calculator frmCalculate = new Calculator();
        frmCalculate.setVisible(true);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        double amount = Double.parseDouble(JOptionPane.showInputDialog("Enter withdraw amount:", 0));
        double balance = Banking_System.balance;
        balance = balance - amount;
        int id = Sign_In.ID;
        
        try {
            Banking_System.DBConnection();
            
            String sql = "UPDATE details SET Balance = ? WHERE (ID = "+id+")";
            PreparedStatement stmt = Banking_System.conn.prepareStatement(sql);
            stmt.setDouble(1, balance);
            stmt.execute();
            
            Banking_System.balance = balance;

            JOptionPane.showMessageDialog(null, "Successful update of balance");

            tAreaTransactions.setText(tAreaTransactions.getText() + "-   R" + String.format("%10.2f", amount) + "\n");
            edtBalance.setText("Your current balance is: R" + String.format("%10.2f", balance));
            
            Banking_System.conn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void edtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDepositActionPerformed
        double amount = Double.parseDouble(JOptionPane.showInputDialog("Enter deposit amount:", 0));
        double balance = Banking_System.balance;
        balance = balance + amount;
        int id = Sign_In.ID;
        
        try {
            Banking_System.DBConnection();
            
            String sql = "UPDATE details SET Balance = ? WHERE (ID = "+id+")";
            PreparedStatement stmt = Banking_System.conn.prepareStatement(sql);
            stmt.setDouble(1, balance);
            stmt.execute();
            
            Banking_System.balance = balance;

            JOptionPane.showMessageDialog(null, "Successful update of balance");

            tAreaTransactions.setText(tAreaTransactions.getText() + "+  R" + String.format("%10.2f", amount) + "\n");
            edtBalance.setText("Your current balance is: R" + String.format("%10.2f", balance));
            
            Banking_System.conn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_edtDepositActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int id = Sign_In.ID;

        try {
            Banking_System.DBConnection();
            
            double dbalance = Banking_System.balance;
            edtBalance.setText("Your current balance is: R" + String.format("%10.2f", dbalance));
            
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JTextField edtBalance;
    private javax.swing.JButton edtDeposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tAreaTransactions;
    // End of variables declaration//GEN-END:variables
}
